# Filtering and Sorting Data

In this in-class assignment, we will practice some basic data filtering and sorting with `pandas`. We will use the `chipotle.csv` data file. This file contains information related chipotle sales.

# Exercise 1 (2 points) 

Load `pandas` and `numpy`

In [3]:
import pandas as pd
import numpy as np

# Exercise 2 (2 points)

Create a data-frame called `chipotle` using the data from the `chipotle.csv`.

In [4]:
chipotle = pd.read_csv("chipotle.csv")
chipotle.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [5]:
chipotle.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

# Exercise 3 (8 points)

How many products cost more than $10.00?

In [7]:
chipotle["item_price"] = chipotle["item_price"].str.replace("$", "").astype(float)
chipotle.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [8]:
chipotle.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [9]:
chipotle[(chipotle["quantity"]== 1) & (chipotle["item_price"] > 10)]["item_name"].unique()

<StringArray>
[         'Chicken Bowl',         'Steak Burrito',       'Chicken Burrito',
         'Barbacoa Bowl',        'Veggie Burrito',           'Veggie Bowl',
    'Chicken Soft Tacos',            'Steak Bowl',      'Carnitas Burrito',
         'Carnitas Bowl',      'Barbacoa Burrito', 'Barbacoa Crispy Tacos',
     'Veggie Salad Bowl',         'Chicken Salad',  'Chicken Crispy Tacos',
      'Steak Salad Bowl',     'Veggie Soft Tacos',   'Barbacoa Soft Tacos',
 'Carnitas Crispy Tacos',   'Carnitas Salad Bowl',    'Chicken Salad Bowl',
   'Barbacoa Salad Bowl',      'Steak Soft Tacos',   'Carnitas Soft Tacos',
    'Steak Crispy Tacos']
Length: 25, dtype: str

In [10]:
chipotle[(chipotle["quantity"]== 1) & (chipotle["item_price"] > 10)]["item_name"].nunique()

25

# Exercise 4 (2 points)

Sort by the name of the item

In [11]:
chipotle

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [14]:
chipotle.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

# Exercise 5 (2 points)

What was the quantity of the most expensive item ordered?

In [15]:
chipotle.sort_values(by="item_price", ascending=False)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
...,...,...,...,...,...
3936,1578,1,Canned Soda,[Diet Dr. Pepper],1.09
2922,1162,1,Bottled Water,NaN,1.09
1396,567,1,Canned Soda,[Coca Cola],1.09
2562,1014,1,Canned Soda,[Coca Cola],1.09
1457,591,1,Canned Soda,[Sprite],1.09

# Exercise 6 (2 points)

How many times was a Veggie Salad Bowl ordered?

In [17]:
chipotle[chipotle["item_name"] == "Veggie Salad Bowl"].shape

(18, 5)

# Exercise 7 (3 points)

How many times did someone order more than one Canned Soda?

In [19]:
chipotle[(chipotle["item_name"] == "Canned Soda") & (chipotle["quantity"] > 1)].shape

(20, 5)